name: Ruby on Rails

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [5.0.0, 5.2.3, 6.0.0, master]
        ruby_version: [2.7.x]
        exclude:
          - rails_version: master
            ruby_version: 2.4.x
          - rails_version: 6.0.0
            ruby_version: 2.4.x
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Build and test with Rake
      run: |
        echo "*** manually installing gems"
        gem install nio4r -v '1.2.1'
        gem install nio4r -v '2.5.2'
        gem install html_tokenizer -v '0.0.7'
        gem install jaro_winkler -v '1.5.4'
        echo "*** successful!"
        gem install bundler:1.17.3
        bundle update
        bundle install --retry 3
        bundle exec rake
        bundle exec rubocop
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
